export const ErrorTitle = 'Houston, we have a problem';
export const NoItemsTitle = 'Search for NASA media assets';
export const NoTitle = 'No title';
export const NoURL = '#';
export const NoDesc = 'No description available for this item.';
export const ReturnText = 'Search for more';
export const FullImage = 'Learn more';
export const SearchPlaceholder = 'NASA Asset Search';
export const loadDelay = 250;
