version: 2.1

orbs:
  cypress: cypress-io/cypress@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: yarn run deploy
      - run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DIST_ID_1 --paths "/*"
      - run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DIST_ID_2 --paths "/*"

workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/base-8
          start: 'npm start' # start server before running tests
      - build:
          requires:
            - cypress/run
  version: 2
